### PR TITLE
Calico Enterprise EKS Workshop

### PR DESCRIPTION
**Pull request by calsoftpranavd**
*Issue #, if available:*

Added the following to /eks-workshop/tree/main/content/beginner/120_network-policies/calico-enterprise
1. Calico Enterprise registration page
2. Calico enterprise usecases
3. Lab 1 - Policy Automation and External Access
4. Lab 2 - Visibility and Troubleshooting
5. Lab 3 - Implementing Existing Security Controls in Kubernetes

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by nagi9** [comment]
@brentley - Please review this PR from our team,  As discussed earlier we included step by step labs in it.

**Comment by brentley** [comment]
@nagi9 and @calsoftpranavd it looks like this PR needs to be rebased. I tried to do it myself, but it doesn't appear that you've granted permission to the upstream to allow commits on your branch. I see 300+ changed files, though... that seems unexpected. Can you check if that condition still exists after rebasing?

**Comment by nagi9** [comment]
> @nagi9 and @calsoftpranavd it looks like this PR needs to be rebased. I tried to do it myself, but it doesn't appear that you've granted permission to the upstream to allow commits on your branch. I see 300+ changed files, though... that seems unexpected. Can you check if that condition still exists after rebasing?

Hi @brentley - You should have the edit permissions now and that's correct it's over 300+ we added all 3 labs step by step as per our earlier discussion. please do let us know if anything missing.

**Comment by nagi9** [comment]
Hi Brent,

Granted the edit permissions last week and should able to modify now,
please do let us know if any issues,

That's correct - we included all 3 labs per our conversation earlier, need
your help in getting the EKS workshop for the Calico Ent Registration page
online first,

Thanks,
Nagi Vumma

**Pull request closed without merging**
