### PR TITLE
Helm module updates

### PR DESCRIPTION
**Pull request by tlliddle**
The `Helm` module needed updating to reflect reflect changes in creating helm templates and output from the various commands in the module.

- Added a table to outlines the different directories and files created with `helm create`
- Updated various screenshots from `helm search` to reflect recent changes in Chart and App Versions.
- Updated various screenshots from `kubectl` commands to reflect what the user will see when performing the module.

Tested this PR with the following EKS versions:
- [x] 1.19
- [x] 1.20

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by tlliddle** [comment]
Hi @adamjkeller or @brentley 
Could you review and merge this PR?

**Comment by tlliddle** [comment]
@jlbutler or @rothgar - Could you review this request?

**Comment by tlliddle** [comment]
@jlbutler or @rothgar - Could you review this request?

**Review by buzzsurfr — APPROVED** [review]
LGTM :shipit:

**Pull request merged**
