### PR TITLE
Update token request to aws-iam-authenticator

### PR DESCRIPTION
**Pull request by BenFields724**
Command to request the token for logging into the Kubernetes dashboard needs to be updated to use the aws-iam-authenticator

*Issue #, if available:*
#740

*Description of changes:*
Update the shown command to be aws-iam-authenticator token instead of aws eks get-token

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by BenFields724** [comment]
Could also use the --token-only flag with aws-iam-authenticator if we want to eliminate the extra step of piping into jq for parsing. Both provide the required token.

**Comment by otterley** [comment]
`aws eks get-token` uses aws-iam-authenticator under the hood. Why do you believe that this needs to be changed? Is something broken?

**Comment by BenFields724** [comment]
Call fails when trying to call it with aws eks get-token. Something must be broken. Using the current command you get the following.
image

**Comment by BenFields724** [comment]
The screenshot shown in the example actually uses the aws-iam-authenticator command as well. So not sure where the two diverged.

**Comment by paavan98pm** [comment]
Hi - could you check if this is still an issue when using the latest aws cli v2? Instructions are available here. https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html

I've raised a PR (#744) to fix this.

**Comment by BenFields724** [comment]
Can confirm that after updating with aws-cli v2 the aws eks get-token command works correctly.

**Comment by BenFields724** [comment]
Addressed in commit 8c074fa.

**Comment by brentley** [comment]
awesome! we ended up pushing instructions to upgrade aws-cli to the
latest version, which should enable the get-token function to work as
written. we'll explore moving to the v2 cli with more comprehensive testing
down the road.

Thanks!
--------
Brent
--------

**Pull request closed without merging**
