### PR TITLE
Update dashboard.md

### PR DESCRIPTION
**Pull request by bird-jtime**
I think this link has changed(?)

*Issue #, if available:* Link for dashboard YAML file is broken

*Description of changes:* Just update the path for the dashboard link. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by oak2278** [comment]
@bird-jtime - Did you get this working? I just used your link and it's working for me.

**Comment by bird-jtime** [comment]
@oak2278 rad! is probably user-error on my part, will try it again

**Comment by bird-jtime** [comment]
@oak2278 rad! is probably user-error on my part, will try it again

**Comment by dalbhanj** [comment]
closing due to https://github.com/aws-samples/eks-workshop/pull/236 merge

**Pull request closed without merging**
