### PR TITLE
X-Ray module link fixes

### PR DESCRIPTION
**Pull request by rnzsgh**
*Issue #, if available:*

NA

*Description of changes:*

Fix links back to the Git repo.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by oak2278** [comment]
We should move these files into the workshop content rather than linking back to github

**Comment by rnzsgh** [comment]
I am open to discussing, but I would like to expose these folders as something someone could pull down locally, copy and use in their own testing.

**Comment by oak2278** [comment]
we can package the files for download. you just need to create a folder <pagename>.files under the module and then add a shortcode into the page similar to https://github.com/aws-samples/eks-workshop/blob/master/content/logging . I'm about to go through the module now. I can take care of this

**Comment by rnzsgh** [comment]
Thanks. Please leave the link to the source code in the module, unless you have a good way to do this in hugo.

**Pull request merged**
