### PR TITLE
Tigera branch backport of current msater

### PR DESCRIPTION
**Pull request by liljenstolpe**
*Issue #, if available:*

*Description of changes:*

I've updated the TSCE install instructions for version 1.0.1 and the cloud9 environment.  I have also backported a few other install instructions (eksctl and k8stools) that had the incorrect versioning.

This should fix eksworkshop.com/tigera - we need to do more to fully show TSCE in the master branch - but this at least gets the tigera branch working again.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by liljenstolpe** [comment]
I can't see the output of the codebuild failure.  Can someone send me the errors, so I can look at it?

**Comment by brentley** [comment]
@liljenstolpe here you go: 
[Container] 2019/01/08 19:11:58 Running command npm run theme
npm ERR! missing script: theme
 npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2019-01-08T19_11_59_003Z-debug.log
 [Container] 2019/01/08 19:11:59 Command did not exit successfully npm run theme exit status 1
[Container] 2019/01/08 19:11:59 Phase complete: BUILD Success: false
[Container] 2019/01/08 19:11:59 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: npm run theme. Reason: exit status 1

**Comment by brentley** [comment]
You probably need to pull in package.json from master.

**Comment by liljenstolpe** [comment]
Ok, thank's @brentley.

**Comment by liljenstolpe** [comment]
Ok, next fail....

**Pull request merged**
