### PR TITLE
Update X-Ray lab to use IAM roles for service accounts

### PR DESCRIPTION
**Pull request by trevorrobertsjr**
*Issue #, if available:*

*Description of changes:*
Updated the X-Ray lab to use an IAM role with a service account for the X-Ray daemonset. Changed the docker image for the X-Ray daemon to include the AWS CLI so that it can use the role ARN to access X-Ray.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by brentley** [comment]
Thanks! I'll test this out tomorrow.

**Comment by brentley** [comment]
I think if you add:
```
eksctl delete iamserviceaccount --name xray-daemon --cluster eksworkshop-eksctl
```
in cleanup.md, replacing the `aws iam` command above, and update the explanation, we'd be good to merge.

**Comment by brentley** [comment]
done!

**Comment by trevorrobertsjr** [comment]
Thank you for the catch, @brentley! I'll keep it in mind for next time, and apologies for missing the notification!

**Pull request merged**
