### PR TITLE
Provide persisted model to unblock inference

### PR DESCRIPTION
**Pull request by Jeffwan**
*Issue #, if available:*

*Description of changes:*
Provide persisted model to unblock inference if user meet problem in training chapter. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by Jeffwan** [comment]
@arun-gupta @dalbhanj

**Comment by brentley** [comment]
Can't we put this artifact into the workshop content, rather than building an external dependency?

**Comment by dalbhanj** [comment]
@brentley, I'm guessing the size of model is big. This is temporary workaround until we figure out the intermittent issue with this chapter.

**Comment by Jeffwan** [comment]
@brentley @dalbhanj 

Good point. It would be better to host in the workshop. Otherwise, we have to maintain external sources. I will try to reduce the model size and then create a follow up PR.

**Pull request merged**
