### PR TITLE
kubeflow/Model training: Remove distracting docker build language

### PR DESCRIPTION
**Pull request by otterley**
Remove docker build instructions from Model Training subchapter.  The student isn't going to do it anyway, and it could be distracting.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by Jeffwan** [comment]
/lgtm
looks good to me

**Comment by cfregly** [comment]
Two of the most-asked questions, in my experience, is “where did this Docker image come from?” and “How do I create this image with my own model?”

Can this move to an appendix section perhaps?  I think it’s still useful.

**Comment by otterley** [comment]
@cfregly I don't see why not.  Can you suggest some verbiage?

**Comment by brentley** [comment]
It looks like this was addressed in a different PR... going to close, but if you feel strongly, please reopen and fix the merge conflict.

**Pull request closed without merging**
