### PR TITLE
Use python3 for inference

### PR DESCRIPTION
**Pull request by raykrueger**
We describe installing tensorflow via python3 and pip3, then execute the inference script via `python`. This change tells the user to execute the inference client via python3.

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by brentley** [comment]
@dalbhanj would you mind checking this one out? Is python3 part of the cloud9 build?

**Comment by dalbhanj** [comment]
@brentley, yes. Python3 is part of Cloud9
@raykrueger, what's the issue with using python2 for this step? we simply use python3 to install tensorflow but I don't see any other dependencies to continue using it.

**Comment by raykrueger** [comment]
@dalbhanj That is the answer. We install tensorflow in python3. Running the inference script with python2 does not work.

**Comment by dalbhanj** [comment]
Thanks. Let me validate and update this PR.

**Comment by dalbhanj** [comment]
python in Cloud9 defaults to python3 in the latest version in us-west-2. 
@raykrueger can you validate this? 

$ which python
alias python='python36'
        /usr/bin/python36

**Comment by raykrueger** [comment]
My environment is long gone, and I may not have even been using Cloud9.

More importantly, don't we want the docs to be consistent? Why confuse the reader with two different versions "python and python3" regardless of the alias. Why not change them all to python if we're going to rely on the alias?

**Comment by dalbhanj** [comment]
Closing this PR. Sorry @raykrueger for closing it. I don't think this adds value for the tutorial

**Pull request closed without merging**
