### PR TITLE
curl fails with 404. Changing to working one

### PR DESCRIPTION
**Pull request by sg09**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by pjlewisuk** [comment]
This change is related to #1370 and https://github.com/aws/karpenter/issues/1622

@jicowan should we go ahead and merge this as a temporary workaround, or wait for the upstream fix from the karpenter team?

**Comment by jicowan** [comment]
Go ahead and merge it

**Review by pjlewisuk — APPROVED** [review]
LGTM

**Comment by pjlewisuk** [comment]
@sg09 there are conflicts in your PR, please rebase against the main branch and update your PR, which I'll then merge. Thanks!

**Comment by ROunofF** [comment]
This was fixed in the recent Karpenter update

**Pull request closed without merging**
