### PR TITLE
replace ClusterIP with NodePort in output; fix syntax highlighting

### PR DESCRIPTION
**Pull request by alexei-led**
*Issue #, if available:*
Wrong service type for `prometheus-server` `ClusterIP`

*Description of changes:*

Changed `prometheus-server` service type (in output) for `NodePort`

p.s.: also fixed syntax highlighting in markdown for the updated page.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by alexei-led** [comment]
And by the way, IMHO, it's not a good advice to open service as NodePort to the whole world. Why no to use `kubectl port-forward`?

**Comment by oak2278** [comment]
@brentley We use NodePort in this example because port-forwarding to Cloud9 is challenging. It's probably worth calling this out in a warning that it is not a best practice

**Comment by dalbhanj** [comment]
Hi fellows, the notice is already there. Can you tell me what is missing from the description below?

"Search for ## List of IP addresses at which the Prometheus server service is available, add nodePort: 30900 and change the type to NodePort as indicated below. Because Prometheus is exposed as ClusterIP by default, the web UI cannot be reached outside of Kubernetes. The reason we are adding NodePort here is for viewing the web UI from worker node IP address. This configuration is not recommended in Production and there are better ways to secure it. You can read more about exposing Prometheus web UI in this link"

**Comment by dalbhanj** [comment]
I'm good with this PR though. If you all are good, let's merge it

**Pull request merged**
