### PR TITLE
Syntax error

### PR DESCRIPTION
**Pull request by FabioChiodini**
Changed
aws appmesh list-meshes
To
aws app mesh list-meshes

As command was wrong and displayed a 403 error

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by brentley** [comment]
Hi @FabioChiodini 

Can you let us know what version of awscli you are using? The one installed on my cloud9 is:

```
aws --version
aws-cli/1.18.17 Python/2.7.16 Linux/4.14.165-103.209.amzn1.x86_64 botocore/1.15.17
```

If I run the following to validate your proposed command, I get an error code:
```
aws app mesh help &>/dev/null; echo $?                                                                
2
```

But If I run the command as written, I get a success code:
```
aws appmesh help &>/dev/null; echo $?
0
```

Can you let us know if you're seeing something different?

**Comment by FabioChiodini** [comment]
Hi @brentley 

I was using version 1.18.26 (had to upgrade it in Cloud9 from 1.16,as some others command were failing). If you see this working in other versions of AWS CLI please ignore my comment.

Thank you very much for the quick reply :)

F.

**Comment by brentley** [comment]
```
brent:~/environment $ aws app mesh help &>/dev/null; echo $?
2
brent:~/environment $ aws appmesh help &>/dev/null; echo $?                                                            
0
brent:~/environment $ aws --version
aws-cli/1.18.26 Python/2.7.16 Linux/4.14.165-103.209.amzn1.x86_64 botocore/1.15.26
```

I installed the same version of awscli, and still see an error with the proposed command. Is there some other possibility for the 403 error? Can you try again with each command to confirm validity?

**Comment by FabioChiodini** [comment]
Hi Brent

Unfortunately I've teared down the environment already. I plan to retake it
soon so I'll check again and eventually open up a log.

Thank you very much for your help!!

Have a great day :)

F.

**Comment by brentley** [comment]
thanks! to you too! I'll close this for now. please reopen when you're able to confirm.

**Pull request closed without merging**
